FROM openjdk:24-ea-17-jdk-slim-bullseye
WORKDIR /workspaces/app

# Instalaciones
RUN apt-get update && apt-get install -y maven git curl zsh && apt-get clean && rm -rf /var/lib/apt/lists/*

# Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" \
    && mkdir -p ~/.plugins/zsh-autosuggestions \
    && mkdir -p ~/.plugins/zsh-syntax-highlighting \
    && git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions.git ~/.plugins/zsh-autosuggestions \ 
    && echo "source ~/.plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc \
    && git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.plugins/zsh-syntax-highlighting \ 
    && echo "source ~/.plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc
