FROM python:3.9-alpine
WORKDIR /workspaces/app

RUN apk update && apk upgrade && apk add --no-cache git curl zsh \
    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" \
    && mkdir -p ~/.plugins/zsh-autosuggestions \
    && mkdir -p ~/.plugins/zsh-syntax-highlighting \
    && git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions.git ~/.plugins/zsh-autosuggestions \ 
    && echo "source ~/.plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc \
    && git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.plugins/zsh-syntax-highlighting \ 
    && echo "source ~/.plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc
